version: 2.1

orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.3.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
  eb: circleci/aws-elastic-beanstalk@1.0.0
  
jobs:
  CICD:
    docker:
      - image: "cimg/base:stable"
    steps:
        - node/install
        - checkout
        - eb/setup
        - aws-cli/install
        - aws-cli/setup

        - run:
            name: Install Frontend node_modules
            command: npm run fe-install
        - run:
            name: Install Backend node_modules
            command: npm run be-install
        - run:
            name: Frontend build
            command: npm run fe-build
        - run:
            name: Backend build
            command: npm run be-build
        - run:
            name: Backend deploy
            command: npm run be-deploy
        - run:
            name: Frontend deploy
            command: npm run fe-deploy
workflows:
  deploy:
    jobs:
      - CICD:
          filters:
            branches:
              only: [main]

